ruby '2.4.1'
source 'https://rubygems.org'

gem 'rails', '4.2.8'
gem 'pg', '~> 0.20.0'
gem 'sass-rails', '~> 5.0'
gem 'bootstrap-sass', '~> 3.3.6'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'slim-rails'
gem 'devise'
gem 'simple_form'
gem 'nested_form'
gem 'rails_utils'
gem 'active_link_to'
gem 'seedbank'
gem 'enumerize'
gem 'cancancan'
gem 'bootstrap_flash_messages'
gem 'react-rails'
gem 'bower-rails'
gem 'remotipart'
gem 'sprockets', '>= 3.0.0'
gem 'sprockets-es6'
gem 'will_paginate-bootstrap'
gem 'country_select'
gem 'money-rails'
gem 'font-awesome-sass', '~> 4.6.2'
gem 'unicorn'
gem 'paperclip', '~> 4.3.7'
gem 'aws-sdk', '< 2.0'
gem 'paper_trail', '~> 5.2.2'
gem 'google_currency'
gem 'acts-as-taggable-on'
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'
gem 'redis'
gem 'redis-namespace'
gem 'rubyzip', '~> 1.1.0'
gem 'axlsx', '2.1.0.pre'
gem 'axlsx_rails'
gem 'premailer-rails'
gem 'sidekiq'
gem 'sinatra', require: false
gem 'foreman'
gem 'materialize-sass'
gem 'paranoia'
gem 'lograge'
gem 'roo'

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'shoulda'
  gem 'pry-rails'
  gem 'dotenv-rails'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'html2slim'
  gem 'letter_opener'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'quiet_assets'
  gem 'meta_request'
  gem 'bullet'
  gem 'brakeman'
  gem 'rack-mini-profiler'
end

group :test do
  gem 'test_after_commit'
end

gem 'rails_12factor', group: :staging

