default: &default
  domain_name:            'FOODHUB'
  return_email_path:      'order@foodhub.com'
  secret_key_base:        <%= ENV["SECRET_KEY_BASE"] %>
  host:                   <%= ENV["HOST"] %>
  sendgrid_username:      <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password:      <%= ENV["SENDGRID_PASSWORD"] %>
  aws_bucket:             <%= ENV["AWS_BUCKET"] %>
  aws_access_key_id:      <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key:  <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  bullet_enable:          <%= ENV["BULLET_ENABLE"] %>

development:
  <<: *default
  secret_key_base:        02e8c092bca761c9247f0be3443541b413b8766bcfe8d9945c8382e91c7b2f7aeb96aae37caaa0ffd1e92385b4630eefd1cd20e4b4fe077bc59152125c568b10

test:
  secret_key_base:        57beaaef54142c2693dde373fe0377096113519588e7774203c6862e930b0f5344903c0671ac19022f7f0ac8f4f1434afc239ccad9b0bb9b2835b0de92b659ae

production:
  <<: *default